grep -v "fusorSV" intermediate_results/total_duplications-truth_in_fusor.txt | grep "SVSIM_DUP.*1-50bp"  >  intermediate_results/duplications/duplications_fusor_false_negatives_1-50bp.txt
grep -v "fusorSV" intermediate_results/total_duplications-truth_in_fusor.txt | grep "SVSIM_DUP.*50-1Kbp"  >  intermediate_results/duplications/duplications_fusor_false_negatives_50-1Kbp.txt
grep -v "fusorSV" intermediate_results/total_duplications-truth_in_fusor.txt | grep "SVSIM_DUP.*1K-10Kbp"  >  intermediate_results/duplications/duplications_fusor_false_negatives_1K-10Kbp.txt
grep -v "fusorSV" intermediate_results/total_duplications-truth_in_fusor.txt | grep "SVSIM_DUP.*10K-50Kbp"  >  intermediate_results/duplications/duplications_fusor_false_negatives_10K-50Kbp.txt
grep -v "fusorSV" intermediate_results/total_duplications-truth_in_fusor.txt | grep "SVSIM_DUP.*50K-100Kbp"  >  intermediate_results/duplications/duplications_fusor_false_negatives_50K-100Kbp.txt
grep -v "fusorSV" intermediate_results/total_duplications-truth_in_fusor.txt | grep "SVSIM_DUP.*100K-250Kbp"  >  intermediate_results/duplications/duplications_fusor_false_negatives_100K-250Kbp.txt
grep -v "fusorSV" intermediate_results/total_duplications-truth_in_fusor.txt | grep "SVSIM_DUP.*250K-500Kbp"  >  intermediate_results/duplications/duplications_fusor_false_negatives_250K-500Kbp.txt
grep -v "fusorSV" intermediate_results/total_duplications-truth_in_fusor.txt | grep "SVSIM_DUP.*500K-1Mbp"  >  intermediate_results/duplications/duplications_fusor_false_negatives_500K-1Mbp.txt

grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*1-50bp" >  intermediate_results/inversions/inversions_fusor_false_negatives_1-50bp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*50-2500bp" >  intermediate_results/inversions/inversions_fusor_false_negatives_50-2500bp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*2500-3500bp" >  intermediate_results/inversions/inversions_fusor_false_negatives_2500-3500bp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*3500-45Kbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_3500-45Kbp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*45K-80Kbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_45K-80Kbp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*80K-115Kbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_80K-115Kbp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*115K-180Kbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_115K-180Kbp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*180K-260Kbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_180K-260Kbp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*260K-300Kbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_260K-300Kbp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*300K-375Kbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_300K-375Kbp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*375K-500Kbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_375K-500Kbp.txt
grep -v "fusorSV" intermediate_results/total_inversions-truth_in_fusor.txt | grep "SVSIM_INV.*500K-1Mbp" >  intermediate_results/inversions/inversions_fusor_false_negatives_500K-1Mbp.txt

grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*1-50bp" > intermediate_results/deletions/deletions_fusor_false_negatives_1-50bp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*50-100bp" > intermediate_results/deletions/deletions_fusor_false_negatives_50-100bp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*100-400bp" > intermediate_results/deletions/deletions_fusor_false_negatives_100-400bp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*400-600bp" > intermediate_results/deletions/deletions_fusor_false_negatives_400-600bp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*600-950bp" > intermediate_results/deletions/deletions_fusor_false_negatives_600-950bp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*950-1.2Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_950-1.2Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*1.2K-1.5Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_1.2K-1.5Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*1.5K-1.9Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_1.5K-1.9Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*1.9K-2.2Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_1.9K-2.2Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*2.2K-2.9Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_2.2K-2.9Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*2.9K-3.6Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_2.9K-3.6Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*3.6K-4.8Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_3.6K-4.8Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*4.8K-6.1Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_4.8K-6.1Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*6.1K-9Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_6.1K-9Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*9K-18.5Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_9K-18.5Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*18.5K-100Kbp" > intermediate_results/deletions/deletions_fusor_false_negatives_18.5K-100Kbp.txt
grep -v "fusorSV" intermediate_results/total_deletions-truth_in_fusor.txt | grep "SVSIM_DEL.*100K-1Mbp" > intermediate_results/deletions/deletions_fusor_false_negatives_100K-1Mbp.txt
