python3 00_scripts/1_analyze_overlap/get_pairwise_overlap_between_callers.py 00_scripts/1_analyze_overlap/config_files/pairwise/deletions_high_confidence-cnv.conf deletion
python3 00_scripts/1_analyze_overlap/get_pairwise_overlap_between_callers.py 00_scripts/1_analyze_overlap/config_files/pairwise/duplications_high_confidence-cnv.conf duplication
python3 00_scripts/1_analyze_overlap/get_pairwise_overlap_between_callers.py 00_scripts/1_analyze_overlap/config_files/pairwise/inversions_high_confidence.conf inversion
