grep -v "SVSIM_DUP" intermediate_results/total_duplications-fusor_in_truth.txt | grep "fusorSV.*1-50bp" > intermediate_results/duplications/duplications_fusor_false_positives_1-50bp.txt
grep -v "SVSIM_DUP" intermediate_results/total_duplications-fusor_in_truth.txt | grep "fusorSV.*50-1Kbp" > intermediate_results/duplications/duplications_fusor_false_positives_50-1Kbp.txt
grep -v "SVSIM_DUP" intermediate_results/total_duplications-fusor_in_truth.txt | grep "fusorSV.*1K-10Kbp" > intermediate_results/duplications/duplications_fusor_false_positives_1K-10Kbp.txt
grep -v "SVSIM_DUP" intermediate_results/total_duplications-fusor_in_truth.txt | grep "fusorSV.*10K-50Kbp" > intermediate_results/duplications/duplications_fusor_false_positives_10K-50Kbp.txt
grep -v "SVSIM_DUP" intermediate_results/total_duplications-fusor_in_truth.txt | grep "fusorSV.*50K-100Kbp" > intermediate_results/duplications/duplications_fusor_false_positives_50K-100Kbp.txt
grep -v "SVSIM_DUP" intermediate_results/total_duplications-fusor_in_truth.txt | grep "fusorSV.*100K-250Kbp" > intermediate_results/duplications/duplications_fusor_false_positives_100K-250Kbp.txt
grep -v "SVSIM_DUP" intermediate_results/total_duplications-fusor_in_truth.txt | grep "fusorSV.*250K-500Kbp" > intermediate_results/duplications/duplications_fusor_false_positives_250K-500Kbp.txt
grep -v "SVSIM_DUP" intermediate_results/total_duplications-fusor_in_truth.txt | grep "fusorSV.*500K-1Mbp" > intermediate_results/duplications/duplications_fusor_false_positives_500K-1Mbp.txt

grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*1-50bp" > intermediate_results/inversions/inversions_fusor_false_positives_1-50bp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*50-2500bp" > intermediate_results/inversions/inversions_fusor_false_positives_50-2500bp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*2500-3500bp" > intermediate_results/inversions/inversions_fusor_false_positives_2500-3500bp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*3500-45Kbp" > intermediate_results/inversions/inversions_fusor_false_positives_3500-45Kbp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*45K-80Kbp" > intermediate_results/inversions/inversions_fusor_false_positives_45K-80Kbp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*80K-115Kbp" > intermediate_results/inversions/inversions_fusor_false_positives_80K-115Kbp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*115K-180Kbp" > intermediate_results/inversions/inversions_fusor_false_positives_115K-180Kbp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*180K-260Kbp" > intermediate_results/inversions/inversions_fusor_false_positives_180K-260Kbp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*260K-300Kbp" > intermediate_results/inversions/inversions_fusor_false_positives_260K-300Kbp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*300K-375Kbp" > intermediate_results/inversions/inversions_fusor_false_positives_300K-375Kbp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*375K-500Kbp" > intermediate_results/inversions/inversions_fusor_false_positives_375K-500Kbp.txt
grep -v "SVSIM_INV" intermediate_results/total_inversions-fusor_in_truth.txt | grep "fusorSV.*500K-1Mbp" > intermediate_results/inversions/inversions_fusor_false_positives_500K-1Mbp.txt

grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*1-50bp" > intermediate_results/deletions/deletions_fusor_false_positives_1-50bp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*50-100bp" > intermediate_results/deletions/deletions_fusor_false_positives_50-100bp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*100-400bp" > intermediate_results/deletions/deletions_fusor_false_positives_100-400bp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*400-600bp" > intermediate_results/deletions/deletions_fusor_false_positives_400-600bp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*600-950bp" > intermediate_results/deletions/deletions_fusor_false_positives_600-950bp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*950-1.2Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_950-1.2Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*1.2K-1.5Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_1.2K-1.5Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*1.5K-1.9Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_1.5K-1.9Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*1.9K-2.2Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_1.9K-2.2Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*2.2K-2.9Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_2.2K-2.9Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*2.9K-3.6Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_2.9K-3.6Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*3.6K-4.8Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_3.6K-4.8Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*4.8K-6.1Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_4.8K-6.1Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*6.1K-9Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_6.1K-9Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*9K-18.5Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_9K-18.5Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*18.5K-100Kbp" > intermediate_results/deletions/deletions_fusor_false_positives_18.5K-100Kbp.txt
grep -v "SVSIM_DEL" intermediate_results/total_deletions-fusor_in_truth.txt | grep "fusorSV.*100K-1Mbp" > intermediate_results/deletions/deletions_fusor_false_positives_100K-1Mbp.txt
